# Generated by Django 5.2.3 on 2025-06-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('enrollment_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_id', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
