# Generated by Django 5.2.3 on 2025-06-28 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('letter_grade', models.CharField(max_length=2)),
                ('semester', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.courses')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.students')),
            ],
            options={
                'unique_together': {('students', 'courses', 'semester')},
            },
        ),
    ]
